AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  apex-crafting-bot

  Get crafting rotation info in Apex Legends

Globals:
  Function:
    Timeout: 10

Resources:
  CronFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.run
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CronEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(5 18 * * ? *)'
            Name: RotationSchedule
            Description: Check at rotation time
